### ISSUE TITLE
AtCoder Copy Contest ID - ウィンドウ幅が狭い時のボタンの表示位置を適切にする

### ISSUE THREAD

**Issue by xe-o** [xe-o/atcoder-userscripts#2]
ページの表示幅が狭い時、AtCoder Copy Contest ID の コピーボタンがコンテスト名から離れてしまう。

これは、AtCoder の以下のようなスタイルに起因している。

```css
@media (max-width: 991px) {
  .contest-title {
    width: 350px;
  }
}
```

**Comment by xe-o** [comment]
以下のようにスタイルを上書きすることで解決した。

```css
@media (max-width: 991px) {
  .contest-title {
    width: auto;
  }
}
```
