### ISSUE TITLE
AtCoder Copy Contest ID - コンテスト名が長い場合の表示を最適化する

### ISSUE THREAD

**Issue by xe-o** [xe-o/atcoder-userscripts#3]
#2 において、ウィンドウ幅が狭い際のボタン表示位置がコンテスト名から離れてしまう問題を、以下のようなスタイルを適用することで対応した。

```css
@media (max-width: 991px) {
  .contest-title {
    width: auto;
  }
}
```

しかし、これではコンテスト名がすべて表示されてしまうため、コンテスト名やユーザー名の表示領域が広い場合にナビゲーションバーが2列で表示されてしまう。
